<?php

namespace Database\Seeders;

use App\Models\OoapTblReqform;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReqformSeeder extends Seeder
{

    public function run()
    {
        OoapTblReqform::truncate();

        DB::table('ooap_tbl_reqform')->insert([
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0001',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '10',
                'people_qty' => '15',
                'total_amt' => '10000',
                'status' => '1',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0002',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '10',
                'people_qty' => '10',
                'total_amt' => '5000',
                'status' => '2',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0003',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '14',
                'people_qty' => '10',
                'total_amt' => '15000',
                'status' => '3',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0004',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '15',
                'total_amt' => '10000',
                'status' => '4',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0005',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '10',
                'people_qty' => '10',
                'total_amt' => '10000',
                'status' => '4',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0006',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '9',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0007',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '1',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0008',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '3',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0009',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '4',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0010',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '4',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0011',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '9',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0012',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '1',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0013',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '1',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0014',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '2',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0015',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '3',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0016',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '4',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0017',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '9',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0018',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '1',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0019',
                'dept_id' => '1',
                'acttype_id' => '1',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '2',
                'created_by' => 'admin'
            ],
            [
                'fiscalyear_code' => '2565',
                'reqform_no' => 'RF-65-0020',
                'dept_id' => '1',
                'acttype_id' => '2',
                'coursegroup_id' => '1',
                'coursesubgroup_id' => '1',
                'course_id' => '1',
                'actname' => 'xxxxxxx',
                'troubletype_id' => '1',
                'moo' => '1',
                'province_id' => '1',
                'amphur_id' => '1',
                'tambon_id' => '1',
                'plan_startdate' => '2022-12-01',
                'plan_enddate' => '2022-12-30',
                'day_qty' => '15',
                'people_qty' => '20',
                'total_amt' => '10000',
                'status' => '3',
                'created_by' => 'admin'
            ],
        ]);
    }
}
